### ISSUE TITLE
About the distribution of relative rotation

### ISSUE THREAD

**Issue by qihangran** [akashsengupta1997/HierarchicalProbabilistic3DHuman#1]
Hi...
Thanks for the great job!
And I have a question:
In part <**3.4. Body shape and pose distribution prediction**>, 
> Here, each joint is modelled independently of all the other joints. Thus, the matrix parameter of the i-th joint, `F_i` , is a function of the input X only.  

As you mentioned in the paper that the probability density function of each joint’s relative rotation matrix is a matrix-Fisher
distribution conditioned on the parents of that joint in the kinematic tree. 
So I am confused that why  you can model each joint independently as "each joint is modelled independently of all the other joints"  ....

**Comment by akashsengupta1997** [comment]
Hi!

Sorry if this was unclear in the paper - we compare 2 different architectures in our ablation study: "Independent" and "Hierarchical" (see Table 1). The joints are modelled independently only for the "Independent" architecture (Equation 5). Later in section 3.4, we point out that this is not a good idea (as you have noted yourself) and introduce the "Hierarchical" architecture (Equation 6), which is one of the main contributions of the paper.

Hope this clears it up.
