### ISSUE TITLE
Projecting predicted vertices given predicted camera

### ISSUE THREAD

**Issue by itzsid** [akashsengupta1997/HierarchicalProbabilistic3DHuman#10]
Hi, 

I'm interested in projecting the predicted vertices given the predicted camera. There is a a functionality in STRAPS for this: 
```
                pred_vertices2d = orthographic_project_torch(pred_vertices, pred_cam_wp)
                pred_vertices2d = undo_keypoint_normalisation(pred_vertices2d,
                                                              proxy_rep_input_wh)
```

Is there something similar in [HierarchicalProbabilistic3DHuman](https://github.com/akashsengupta1997/HierarchicalProbabilistic3DHuman)? I would like to avoid using `body_vis_renderer`. 

Thanks!

**Comment by akashsengupta1997** [comment]
Hi,

Yes the same functions are available in this repo!

`orthographic_project_torch ` is [here](https://github.com/akashsengupta1997/HierarchicalProbabilistic3DHuman/blob/9893133313afa0cc22323263b1df16871c36ae74/utils/cam_utils.py#L9) and `undo_keypoint_normalisation ` is [here](https://github.com/akashsengupta1997/HierarchicalProbabilistic3DHuman/blob/9893133313afa0cc22323263b1df16871c36ae74/utils/joints2d_utils.py#L5).
