### ISSUE TITLE
Downloading time of the background file

### ISSUE THREAD

**Issue by 0scarJ1ang** [akashsengupta1997/HierarchicalProbabilistic3DHuman#12]
Dear akash,

Thank you very much for the amazing work! When I tried to download the background files, it said I would probably need two weeks due to the slow downloading speed in google colab (I tried several different high-speed internets). Can I ask how you download them, or do you have a downloaded version already in your google drive that you can share?

Thanks again! :)

**Comment by akashsengupta1997** [comment]
Hi Oscar, by background files do you mean the LSUN background images?

**Comment by noahcao** [comment]
yes, I wonder how to manage and download the LSUN dataset? Also, its training set actually contains more than 397582  images, how to sample the subset?
