### ISSUE TITLE
run_predict.py generates output with same image

### ISSUE THREAD

**Issue by chillcloud-dev** [akashsengupta1997/HierarchicalProbabilistic3DHuman#6]
Hello 
first of all - nice Job. 

I am doing right now a research project regarding self collision and i would like to use your repo as a baseline to generate 3d avatars of people. 

I ran your run_predict.py successfully but noticed that the output image contains multiple smaller, identical images. 
I was expecting something similar as the teaser.png where u have the estimated 3d mesh of the person. 

Could you please tell me how to reproduce this visualization? I would like to get the 3d mesh and use it as a mask to overlap with a pointcloud.. 

I would appreciate your help 

Thanks

**Comment by akashsengupta1997** [comment]
Hi,

The output image from the demo should show the mode of the predicted shape and pose SMPL parameter distributions, as well as some samples from the distribution. The parameter distributions are visualised by converting the SMPL parameters into SMPL body meshes, and rendering these meshes using multiple global rotations (to give different camera viewpoints).

The teaser GIF is simply obtained by gradually rotating some predicted sample meshes and rendering them.

If you want to save any 3D body mesh, you can save the mode predicted vertices (`pred_vertices_mode` in the code) or predicted samples  (`pred_vertices_samples` in the code). The format in which they are saved is up to you. They can be saved as an obj file if you want to use them in other applications: https://github.com/akashsengupta1997/HierarchicalProbabilistic3DHuman/issues/2.

**Comment by akashsengupta1997** [comment]
Please see #11.
